<a href="https://colab.research.google.com/github/Krawieckk/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


In [2]:
import numpy as np

In [ ]:
x = np.array([[2, 3, 4], [4, 7, 12]])
x

array([[ 2,  3,  4],
       [ 4,  7, 12]])

In [ ]:
x.ndim

2

In [ ]:
x.size

6

In [ ]:
x.shape

(2, 3)

Typy danych

In [ ]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [ ]:
a = np.array([1.0, 2.3, 3.3])
a.dtype

dtype('float64')

In [ ]:
a = np.array([1, 2, 3], dtype='float')
a.dtype

dtype('float64')

In [ ]:
a

array([1., 2., 3.])

In [ ]:
a = np.array([1, 2, 3], dtype='complex')
a.dtype

dtype('complex128')

In [ ]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
a = np.array([1.0, 2.7, 3.3], dtype='int')
a.dtype

dtype('int64')

In [ ]:
a

array([1, 2, 3])

In [ ]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [ ]:
a = np.array([24, 120, 230], dtype=np.int8)
a.dtype

dtype('int8')

In [ ]:
a = np.array([24, 120, 230], dtype=np.uint8)
a.dtype

dtype('uint8')

Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [ ]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(0, 1, .05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [ ]:
a = np.array([3, 1, 4, 2])
b = np.array([3, -1, 3, 2])
print(a)
print(b)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
a + b

array([6, 0, 7, 4])

In [ ]:
a - b

array([0, 2, 1, 0])

In [ ]:
a * b

array([ 9, -1, 12,  4])

In [ ]:
a / b

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(a, b)

array([6, 0, 7, 4])

In [ ]:
np.subtract(a, b)

array([0, 2, 1, 0])

In [ ]:
np.multiply(a, b)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(a, b)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
a + 3

array([6, 4, 7, 5])

In [ ]:
a + 3*b

array([12, -2, 13,  8])

In [ ]:
x = np.array([[1, 3] , [-2, 0]])
y = np.array([[6, 0] , [-1, 2]])

In [ ]:
np.dot(x, y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
x @ y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [ ]:
np.random.randint(10)

3

In [ ]:
np.random.randint(low=10, high=101)

56

In [ ]:
np.random.randint(10, 101, 10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [ ]:
np.random.choice([4, 2, 1, 2])

2

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([1, 0, 5, 2, 9, 7, 4, 6, 8, 3])

Podstawowe funkcje w bibliotece numpy

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(16)

4.0

In [ ]:
np.all([2, 3, 1])

True

In [ ]:
np.any([1, 0, 0])

True

In [ ]:
a = np.random.rand(5)
a

array([0.60639321, 0.0191932 , 0.30157482, 0.66017354, 0.29007761])

In [ ]:
np.argmax(a)

3

In [ ]:
a[np.argmax(a)]

0.660173537492685

In [ ]:
np.argmin(a)

1

In [ ]:
np.argsort(a)

array([1, 4, 2, 0, 3])

In [ ]:
np.max(a)

0.660173537492685

In [ ]:
np.min(a)

0.019193198309333526

In [ ]:
np.mean(a)

0.37548247476298724

In [ ]:
np.median(a)

0.30157481667454933

In [ ]:
np.std(a)

0.23412268262339708

Indeksowanie i wycinanie tablic

In [3]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
a[2]

2

In [7]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [9]:
a[[0, 3]]

array([0, 3])

In [10]:
a[-1]

19

In [12]:
a = a.reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
a[:, 0]

array([ 0,  5, 10, 15])

In [15]:
a[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [18]:
a[1, 2] = 14
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [19]:
for row in a: print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [20]:
for row in a: print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [21]:
for item in a.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [22]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
a.shape

(4, 5)

In [24]:
a.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [30]:
a = np.arange(-10, 10, 0.5)
a = a.reshape(10, -1)
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [31]:
a > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
a[a > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [33]:
np.bitwise_and(a > -5, a < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
a[np.bitwise_and(a > -5, a < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [37]:
np.bitwise_or(a < -5, a > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])