<a href="https://colab.research.google.com/github/Krawieckk/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

Norma wektora, długość wektora w R^2

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

Norma euklidesowa w R^n

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płasczyźnie

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p-q)

5.0

Odległość dwóch punktów w przestrzeni R^n

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p-q)

5.0990195135927845

Mnożenie macierzy

In [8]:
x = np.array([[5, 3], [3, 9]])
y = np.array([[1], [-1]])
print(x, '\n')
print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [12]:
z = x.dot(y)
z

array([[ 2],
       [-6]])

In [13]:
z.shape

(2, 1)

In [14]:
X = np.array([[2, -1, 3], [3, 1, 0]])
Y = np.array([[2, 1, -1], [0, -1, 2], [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [16]:
X.dot(Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [18]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

Ślad macierzy

In [27]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

Macierz jednostkowa

macierz jednostkowa - macierz kwadratowa, na której na głównej przekątnej są tylko jedynki, a wszędzie indziej zera

In [20]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

A - macierz kwadratowa stopnia n. Macierz A posiada macierz odwrotną, gdy istnieje macierz B, taka, że AB = BA = I (macierz jednostkowa)

In [22]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [24]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [25]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [29]:
A

array([[ 2,  4],
       [-1,  3]])

In [36]:
np.transpose(A)


array([[ 2, -1],
       [ 4,  3]])

In [37]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [38]:
A = np.array([[2, 4], [1, -1]])
print(A)

array([[ 2,  4],
       [ 1, -1]])

In [39]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [41]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])