<a href="https://colab.research.google.com/github/Krawieckk/data-science-bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


In [1]:
import numpy as np

In [17]:
x = np.array([[2, 3, 4], [4, 7, 12]])
x

array([[ 2,  3,  4],
       [ 4,  7, 12]])

In [19]:
x.ndim

2

In [20]:
x.size

6

In [18]:
x.shape

(2, 3)

Typy danych

In [22]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [23]:
a = np.array([1.0, 2.3, 3.3])
a.dtype

dtype('float64')

In [24]:
a = np.array([1, 2, 3], dtype='float')
a.dtype

dtype('float64')

In [25]:
a

array([1., 2., 3.])

In [26]:
a = np.array([1, 2, 3], dtype='complex')
a.dtype

dtype('complex128')

In [27]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [28]:
a = np.array([1.0, 2.7, 3.3], dtype='int')
a.dtype

dtype('int64')

In [29]:
a

array([1, 2, 3])

In [30]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [31]:
a = np.array([24, 120, 230], dtype=np.int8)
a.dtype

dtype('int8')

In [32]:
a = np.array([24, 120, 230], dtype=np.uint8)
a.dtype

dtype('uint8')

Tworzenie tablic

In [33]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [41]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [42]:
np.arange(0, 1, .05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [44]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [45]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
a.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
a.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])