<a href="https://colab.research.google.com/github/Krawieckk/data-science-bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


In [1]:
import numpy as np

In [17]:
x = np.array([[2, 3, 4], [4, 7, 12]])
x

array([[ 2,  3,  4],
       [ 4,  7, 12]])

In [19]:
x.ndim

2

In [20]:
x.size

6

In [18]:
x.shape

(2, 3)

Typy danych

In [22]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [23]:
a = np.array([1.0, 2.3, 3.3])
a.dtype

dtype('float64')

In [24]:
a = np.array([1, 2, 3], dtype='float')
a.dtype

dtype('float64')

In [25]:
a

array([1., 2., 3.])

In [26]:
a = np.array([1, 2, 3], dtype='complex')
a.dtype

dtype('complex128')

In [27]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [28]:
a = np.array([1.0, 2.7, 3.3], dtype='int')
a.dtype

dtype('int64')

In [29]:
a

array([1, 2, 3])

In [30]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [31]:
a = np.array([24, 120, 230], dtype=np.int8)
a.dtype

dtype('int8')

In [32]:
a = np.array([24, 120, 230], dtype=np.uint8)
a.dtype

dtype('uint8')

Tworzenie tablic